name: 🚜 Auto update subtree

on:
  push:
    branches:
      - main
    paths:
      - materialchart/**
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Sync branch using subtree
        run: |
          git subtree push --prefix materialchart origin lib-latest
